<?php

namespace Splitstack\Domainable\Codegen;

use Illuminate\Database\Eloquent\Model;
use ReflectionClass;

/**
 * Option C: generate a per-aggregate domain interface from a model.
 *
 * The interface is the opt-in type-safe contract. Have the model implement it
 * so static analysis checks the #[Domain] methods really exist, and type
 * asEntity() to return it so consumers get real autocomplete on the entity.
 */
final class InterfaceGenerator
{
    use BuildsDomainTypes;

    public function __construct(
        private readonly ?string $namespace = null,
        private readonly string $suffix = 'Entity',
    ) {}

    /**
     * @param  class-string<Model>  $modelClass
     */
    public function generate(string $modelClass): GeneratedFile
    {
        $class = new ReflectionClass($modelClass);
        $model = $class->newInstance();

        $name = $class->getShortName().$this->suffix;
        $namespace = $this->namespace ?? $class->getNamespaceName();

        return new GeneratedFile(
            path: dirname((string) $class->getFileName()).DIRECTORY_SEPARATOR.$name.'.php',
            contents: $this->render($modelClass, $namespace, $name, $model, $class),
        );
    }

    private function render(string $modelClass, string $namespace, string $name, Model $model, ReflectionClass $class): string
    {
        $lines = ['<?php', '', "namespace {$namespace};", ''];

        $lines[] = '/**';
        $lines[] = " * Domain entity contract for \\{$modelClass}.";
        $lines[] = ' *';
        $lines[] = ' * Generated by laravel-entity-model. Re-run to refresh.';

        $properties = $this->attributeTypes($model);
        if ($properties !== []) {
            $lines[] = ' *';
            foreach ($properties as $property => $type) {
                $lines[] = " * @property-read {$type} \${$property}";
            }
        }

        $lines[] = ' */';
        $lines[] = "interface {$name}";
        $lines[] = '{';

        $methods = $this->domainMethods($class);
        foreach ($methods as $index => $method) {
            if ($index > 0) {
                $lines[] = '';
            }
            $lines[] = '    '.$this->methodSignature($method);
        }

        $lines[] = '}';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
